[package]
name = "plaud-stt-obsidian"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.3.0", features = [] }
tauri-plugin-shell = "2.3.4"
tauri-plugin-dialog = "2.3.3"
serde_json = "1.0"

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[profile.release]
strip = true
